"use client";
import { useEffect, useState } from "react";
import { formatFare, formatQuote, parsePnr, type Conversion } from "@/lib/converter";
import ParserDiagnostics from "@/components/ParserDiagnostics";
import { unresolvedBlockers, type ParserReview } from "@/lib/parser/adapter";
const empty = (): Conversion => ({ raw_text: "", pnr_code: "", gds_type: "unknown", status: "draft", fare_amount: 0, fare_currency: "BDT", baggage_info: "", cancellation_rule: "", reissue_rule: "", passengers: [], flights: [], hotels: [] });
const field = "w-full rounded border border-slate-300 bg-white p-2";
async function request(url: string, options?: RequestInit) { const res = await fetch(url, options); const body = await res.json(); if (!res.ok) throw Error(body.error || "Request failed"); return body; }
export default function Home() {
  const [form, setForm] = useState<Conversion>(empty), [history, setHistory] = useState<Conversion[]>([]), [tab, setTab] = useState<"Converter" | "History">("Converter"), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [review, setReview] = useState<ParserReview | null>(null), [reviewConfirmed, setReviewConfirmed] = useState(false), [parsedRaw, setParsedRaw] = useState("");
  const change = (patch: Partial<Conversion>) => { setForm(prev => ({ ...prev, ...patch })); setReviewConfirmed(false); };
  async function refresh() { try { setHistory(await request("/api/conversions")); } catch (e) { setMessage(String(e)); } }
  useEffect(() => { void refresh(); }, []);
  function parse() { if (!form.raw_text.trim()) return setMessage("Paste PNR text first."); const { parserReview, ...result } = parsePnr(form.raw_text); change({ ...result, id: undefined, whatsapp_output: "" }); setReview(parserReview); setParsedRaw(form.raw_text); setReviewConfirmed(false); setMessage(result.flights.length ? "Compare the displayed preview and parser warnings with the original PNR before saving." : "No flights detected. Check the source or add verified flight segments manually."); }
  async function save() { if (!form.flights.length) return setMessage("No flights found. Check the pasted PNR or add the flight segments before saving a quote."); if (!review || parsedRaw !== form.raw_text || !reviewConfirmed) return setMessage("Parse the current PNR and confirm the source review before saving."); if (unresolvedBlockers(review).length) return setMessage("Resolve blocking parser disagreements or unconfirmed flight status before saving."); setBusy(true); try { const saved = await request("/api/conversions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, reviewed_source: true }) }); setForm(saved); await refresh(); setMessage("Conversion saved."); } catch (e) { setMessage(`Save failed: ${String(e)}`); } finally { setBusy(false); } }
  function editList<K extends "passengers" | "flights" | "hotels">(key: K, index: number, property: string, value: string) { change({ [key]: form[key].map((item, i) => i === index ? { ...item, [property]: property === "nights" ? Number(value) : value } : item) }); }
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-900"><div className="mx-auto max-w-5xl space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Travel PNR Converter</h1><p>English quotes and PDF itineraries</p></div><nav className="flex gap-2">{(["Converter", "History"] as const).map(name => <button key={name} className={`rounded px-4 py-2 ${tab === name ? "bg-blue-700 text-white" : "bg-white"}`} onClick={() => { setTab(name); if (name === "History") void refresh(); }}>{name}</button>)}<button className="rounded bg-slate-200 px-4 py-2" onClick={async () => { await fetch("/auth/signout", { method: "POST" }); window.location.assign("/auth/login"); }}>Sign out</button></nav></header>{message && <p role="status" className="rounded bg-blue-50 p-3">{message}</p>}
  {tab === "History" ? <section className="space-y-3"><h2 className="text-xl font-bold">Conversion history</h2>{history.length ? history.map(c => <article key={c.id} className="rounded border bg-white p-4"><strong>{c.pnr_code || "No booking reference"}</strong> · {c.created_at?.slice(0, 10)} · {c.flights.length} flights · Fare: {formatFare(c)}<div className="mt-2 flex gap-4"><button className="text-blue-700 underline" onClick={() => { setForm(c); setReview(null); setReviewConfirmed(false); setTab("Converter"); }}>Open and edit</button><button className="text-blue-700 underline" onClick={() => { const { parserReview } = parsePnr(c.raw_text); setForm(c); setReview(parserReview); setParsedRaw(c.raw_text); setReviewConfirmed(false); setTab("Converter"); setMessage("Review the saved source before downloading its PDF."); }}>Review and download PDF</button><button className="text-red-700 underline" onClick={async () => { if (!confirm("Delete this conversion?")) return; try { await request(`/api/conversions?id=${c.id}`, { method: "DELETE" }); await refresh(); } catch (e) { setMessage(String(e)); } }}>Delete</button></div></article>) : <p>No conversions yet. Create your first quote in Converter.</p>}</section> : <>
  <section className="rounded border bg-white p-4"><h2 className="mb-2 text-xl font-semibold">Raw PNR text</h2><textarea aria-label="Raw PNR text" rows={7} className={field} placeholder="Paste Sabre, Galileo or Amadeus PNR text" value={form.raw_text} onChange={e => { change({ raw_text: e.target.value }); setReview(null); setReviewConfirmed(false); }} /><div className="mt-2 flex gap-3"><button className="rounded bg-blue-700 px-4 py-2 text-white" onClick={parse}>Parse PNR</button><button onClick={() => { setForm(empty()); setReview(null); setReviewConfirmed(false); setParsedRaw(""); }}>New conversion</button></div></section>
  <ParserDiagnostics review={review} />
  {review && <label className="flex items-start gap-2 rounded border bg-white p-3"><input type="checkbox" checked={reviewConfirmed} onChange={e => setReviewConfirmed(e.target.checked)} /><span>I checked passenger names/count, flight count/routes/statuses, local dates, arrival dates and fare conditions against the original PNR. I understand the displayed dates use the older conversion path until local date storage is upgraded.</span></label>}
  <section className="grid gap-3 rounded border bg-white p-4 sm:grid-cols-2"><h2 className="sm:col-span-2 text-xl font-semibold">Fare and conditions</h2>{(["pnr_code", "fare_amount", "fare_currency", "baggage_info", "cancellation_rule", "reissue_rule"] as const).map(key => <label key={key} className="capitalize">{key.replaceAll("_", " ")}<input className={field} type={key === "fare_amount" ? "number" : "text"} placeholder={key === "fare_amount" ? "Enter confirmed fare" : undefined} value={key === "fare_amount" && !form.fare_amount ? "" : form[key] ?? ""} onChange={e => change({ [key]: key === "fare_amount" ? Number(e.target.value) : e.target.value })} /></label>)}</section>
  <section className="space-y-4 rounded border bg-white p-4"><h2 className="text-xl font-semibold">Parsed details</h2>{(["passengers", "flights", "hotels"] as const).map(key => <div key={key}><div className="flex justify-between"><h3 className="font-semibold capitalize">{key} ({form[key].length})</h3><button className="text-blue-700 underline" onClick={() => change({ [key]: [...form[key], key === "passengers" ? { name: "", type: "adult" } : key === "flights" ? { airline: "", flight_number: "", origin: "", destination: "", departure_at: "", arrival_at: "", cabin: "" } : { hotel_name: "", check_in: "", check_out: "", nights: 0, room_type: "" }] })}>Add {key.slice(0, -1)}</button></div>{form[key].map((item, i) => <div key={i} className="my-2 grid gap-2 rounded bg-slate-50 p-3 sm:grid-cols-3">{Object.entries(item).map(([property, value]) => <label className="text-sm capitalize" key={property}>{property.replaceAll("_", " ")}<input className={field} value={value ?? ""} onChange={e => editList(key, i, property, e.target.value)} /></label>)}<button className="text-red-700 underline" onClick={() => change({ [key]: form[key].filter((_, j) => j !== i) })}>Remove</button></div>)}</div>)}</section>
  <section className="space-y-3 rounded border bg-white p-4"><button disabled={busy || !form.raw_text.trim() || !reviewConfirmed || !review || parsedRaw !== form.raw_text || unresolvedBlockers(review).length > 0} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" onClick={save}>{busy ? "Saving..." : form.id ? "Save edits and regenerate" : "Save and generate"}</button>{form.id && review && reviewConfirmed && parsedRaw === form.raw_text && !unresolvedBlockers(review).length && <a className="ml-3 rounded bg-slate-900 px-4 py-2 text-white" href={`/api/conversions/pdf?id=${form.id}`}>Download PDF</a>}{form.id && <div><div className="flex justify-between"><h3 className="font-semibold">WhatsApp quote (English)</h3><button disabled={!review || !reviewConfirmed || !!unresolvedBlockers(review).length} className="text-blue-700 underline disabled:opacity-50" onClick={async () => { await navigator.clipboard.writeText(formatQuote(form)); setMessage("Quote copied."); }}>Copy quote</button></div><pre className="whitespace-pre-wrap rounded bg-slate-100 p-3 font-sans">{formatQuote(form)}</pre></div>}</section>
  </>}</div></main>;
}
